cursor:
  blink_timeout: 1
  style:
    blinking: Always
    shape: Beam

env:
  TERM: xterm-256color

font:

  bold:
    family: MesloLGS Nerd Font
    style: Bold

  bold_italic:
    family: MesloLGS Nerd Font
    style: Bold Italic

  italic:
    family: MesloLGS Nerd Font
    style: Italic

  normal:
    family: MesloLGS Nerd Font
    style: Regular

  size: 10

import:
 - ~/.config/alacritty/themes/themes/iterm.yaml

key_bindings:
  - {
      action: SpawnNewInstance,
      key: Return,
      mods: Alt|Shift,
    }

shell:
  args:
    - -l
    - -c
    - "tmux -u attach || tmux -u"
  program: /usr/bin/zsh

window:
  opacity: 0.9
  padding:
    x: 2
    y: 3
