#!/usr/bin/zsh

wikidir="/usr/share/doc/arch-wiki/html/en/"
wikidocs="$(find ${wikidir} -iname "*.html")"

main() {
    choice=$(printf '%s\n' "${wikidocs[@]}" | \
        cut -d '/' -f8- | \
        sed -e 's/_/ /g' -e 's/.html//g' | \
        sort | \
        wofi --show=dmenu -i -l 20 -p 'Arch Wiki Docs: ') || exit 1

    if [ "$choice" ]; then
        final=$(printf '%s\n' "${wikidir}${choice}.html" | sed 's/ /_/g')
        xdg-open "$final"
    else
        exit 0
    fi
}

main
