#!/usr/bin/zsh

if [ "$EUID" -ne 0 ]; then
    echo "Fan Control requires root user!"
    exit 1
fi

export WAYLAND_DISPLAY=wayland-1
export XDG_RUNTIME_DIR=/run/user/1000

/home/thesheepster/aur/LenovoLegionLinux/python/legion_linux/legion_gui.py
